---
- name: manage user accounts
  user:
    name: "{{ user.login }}"
    shell: /bin/bash
    groups: "{{ user.groups|join(',') }}"
    password: "{{ user.password|default(omit) }}"
    state: "{{ user.state }}"
    remove: yes

- name: add public keys
  authorized_key:
    user: "{{ user.login }}"
    key: "{{ user.public_key }}"
  when: "user.state == 'present'"
