---

- hosts: kube_nodes
  become: true
  roles:
    - role: geerlingguy.pip
      tags:
        - pip
        - kubernetes
    - role: geerlingguy.docker
      tags:
        - docker
        - kubernetes
    - role: geerlingguy.kubernetes
      tags:
        - k8s
        - kubernetes
    - role: print-kube-config
      tags:
        - info
        - kubernetes
